### PR TITLE
Package.json for npm

### LINKED ISSUE #60: npmjs.com repository ?
Hi,

In future, do you distribute your plugin with npmjs.com repository

I find this one in my first research https://www.npmjs.com/package/cordova-plugin-appversion but it's not you :-) 

Regards.

### PR DESCRIPTION
**Pull request by Maistho**
So I made a simple package.json for npm. 
I guess this closes #60 

I also published this to https://www.npmjs.com/package/cordova-plugin-app-version
If you (@whiteoctober) want to get that repo, just say so and I'll transfer it.

Maybe cordova-plugin-app-version isn't the best name, since there's already a [cordova-plugin-appversion](https://github.com/Rareloop/cordova-plugin-app-version), which is very similar.

### CODE REVIEW

**Comment by bau720123** [comment]
thanks @Maistho 
transfer this plugin to npm
good job !!

**Comment by richsage** [comment]
@Maistho that's great - thanks for getting on top of that and sorting it out :-) Let's leave it as the current name, as that's what the plugin has been published under already. If there is confusion further down the line then we can take a look then.

Could you arrange the transfer as well?

**Comment by Maistho** [comment]
Sure, I'll add you! What's your npm account name?

**Comment by richsage** [comment]
Thanks @Maistho - account is `whiteoctober` :-)

**Comment by Maistho** [comment]
Done, you should have access now. =)

**Pull request merged**
