### PR TITLE
add browser platform

### PR DESCRIPTION
**Pull request by marcel-ernst**
have fun

### CODE REVIEW

**Comment by richsage** [comment]
@marcel-ernst please back out the CHANGELOG and version bump changes

**Comment by marcel-ernst** [comment]
ok, check it now.

**Comment by cadesalaberry** [comment]
Any progress ?

**Comment by biesbjerg** [comment]
Would love to see this merged in as well.

**Comment by GonzaloPS** [comment]
Sorry, How can i install this version?

**Comment by euleule** [comment]
Can you merge this please? I just spent hours debugging my tests, until I noticed they fail because of this.

**Comment by cadesalaberry** [comment]
@richsage any plan for a new release with this PR ?

**Comment by richsage** [comment]
@cadesalaberry afraid I don't work at White October anymore - probably one for @WoJBurgess

**Comment by DennisSmolek** [comment]
This looks good to me, 

Can anyone who uses a Browser build confirm the core functions work with this PR?
If not I'll try to find time to do a Browser build of our core app to test this...

@marcel-ernst if you have a hosted version anywhere that would be good enough for me..

**Comment by MattRiddell** [comment]
Yep just added this to my app and it works fine in browser with this patch

**Comment by sampart** [comment]
Thanks for this, @marcel-ernst, and to everyone who tested.

I've merged this now as you'll see, and have created a release to include it: https://github.com/whiteoctober/cordova-plugin-app-version/releases/tag/0.1.10

Note that, although I've got write permissions on this repository, I'm not a maintainer for this project - #100 still applies - I just merged this as it seemed simple, in-demand and well-tested.

**Pull request merged**
