### PR TITLE
Fix deprecation warning regarding Cordova 4.0

### LINKED ISSUE #18: Deprecation warnings in Cordova 3.6.3
I'm seeing the following deprecation warnings when trying to build an app on Cordova 3.6.3 with this plugin:

```
.../Plugins/uk.co.whiteoctober.cordova.appversion/AppVersion.m:16:32: warning: 'toSuccessCallbackString:' is deprecated: Deprecated in Cordova 3.6. Use the CDVCommandDelegate method sendPluginResult:callbackId instead. This will be removed in 4.0.0 [-Wdeprecated-declarations]
    javaScript = [pluginResult toSuccessCallbackString:callbackId];
                               ^
In file included from .../platforms/ios/.../Plugins/uk.co.whiteoctober.cordova.appversion/AppVersion.m:1:
In file included from .../platforms/ios/.../Plugins/uk.co.whiteoctober.cordova.appversion/AppVersion.h:1:
In file included from .../platforms/ios/build/emulator/include/Cordova/CDVPlugin.h:22:
.../platforms/ios/build/emulator/include/Cordova/CDVPluginResult.h:67:1: note: method 'toSuccessCallbackString:' declared here
- (NSString*)toSuccessCallbackString:(NSString*)callbackId CDV_DEPRECATED(3.6, "Use the CDVCommandDelegate method sendPluginResult:callbackId instead. This will be removed in 4.0.0");
^
.../platforms/ios/.../Plugins/uk.co.whiteoctober.cordova.appversion/AppVersion.m:18:11: warning: 'writeJavascript:' is deprecated: Deprecated in Cordova 3.6. Use the CDVCommandDelegate equivalent of evalJs:. This will be removed in 4.0.0 [-Wdeprecated-declarations]
    [self writeJavascript:javaScript];
          ^
In file included from .../platforms/ios/.../Plugins/uk.co.whiteoctober.cordova.appversion/AppVersion.m:1:
In file included from .../platforms/ios/.../Plugins/uk.co.whiteoctober.cordova.appversion/AppVersion.h:1:
.../platforms/ios/build/emulator/include/Cordova/CDVPlugin.h:61:1: note: method 'writeJavascript:' declared here
- (NSString*)writeJavascript:(NSString*)javascript CDV_DEPRECATED(3.6, "Use the CDVCommandDelegate equivalent of evalJs:. This will be removed in 4.0.0");
^
2 warnings generated.
```

### PR DESCRIPTION
**Pull request by oliversalzburg**
Fixes #18

### CODE REVIEW

**Comment by Libbux** [comment]
+1

**Comment by Libbux** [comment]
:+1:

**Comment by richsage** [comment]
Can you rebase this against master?

**Comment by oliversalzburg** [comment]
In theory, probably. In practice, we moved to our own fork long ago after seeing no activity here. I'm not going to invest a single minute of work if the PR is just going to sit here for another year until it can no longer be merged again.

**Comment by richsage** [comment]
Apologies this has taken a few months to review. Would you be happy for your submission to be included anyway (I can sort the rebase)?

**Comment by oliversalzburg** [comment]
Sure. That'd be great :)

**Pull request closed without merging**
