### PR TITLE
Renamed windows8 platform for windows

### PR DESCRIPTION
**Pull request by filionf**
Hi, 

Cordova renamed the windows8 platform for windows some time ago. This pull request is to support this change.

### CODE REVIEW

**Comment by beat-at-hartwig** [comment]
I would really like to see this PR merged!

**Comment by edgahan** [comment]
Can confirm this working on a Windows 10 cordova build - current master branch is not returning anything on `getAppVersion` call. This fixed it.

**Comment by cadesalaberry** [comment]
@whiteoctober, I would love to see this PR merged !

**Comment by richsage** [comment]
Done! :)

**Comment by cadesalaberry** [comment]
That was fast, thanks @richsage !

**Comment by cadesalaberry** [comment]
When do you plan on making a npm release ?

I would have gladly used the github URL as source for my plugin, but I did not really grasp the difference between the `develop` and the `master` branch.

**Comment by richsage** [comment]
ah you're right - my bad, I merged into master as well as develop :-( Let me sort that out; I'll get a new release out today then.

**Comment by richsage** [comment]
@cadesalaberry 0.1.9 has been released.

**Pull request merged**
